name: 'Test action'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git credentials for key manager
      run: |
        git config --global url."https://${{ secrets.REPO_ACCESS_TOKEN }}:x-oauth-basic@github.com/FairgateLabs/".insteadOf "https://github.com/FairgateLabs/"
    - name: Checkout rust-bitvmx-key-manager
      uses: actions/checkout@v4
      with:
        path: main
        submodules: true
    - name: Checkout rust-bitvmx-settings
      uses: actions/checkout@v4
      with:
        repository: FairgateLabs/rust-bitvmx-settings
        ref: main
        path: rust-bitvmx-settings
        submodules: true
    
    - name: Cache Cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ./target
          ./Cargo.lock
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
        
    - name: Build project
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose